# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


def compute():
    n = 4000000
    out = 2
    f1, f2 = 1, 2
    curr = f1 + f2

    while curr <= n:
        if curr % 2 == 0:
            out += curr
        f1 = f2
        f2 = curr
        curr = f1 + f2

    return out


if __name__ == "__main__":
    print(compute())